# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundmgmt', '0002_auto_20171113_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lost_found',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='LOST', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
