# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundmgmt', '0003_auto_20171113_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lost_found',
            new_name='lost_or_found',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/img/default-img.png', upload_to=''),
        ),
    ]
