# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundmgmt', '0008_auto_20171114_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zone',
            field=models.CharField(choices=[('', '----'), ('koshi', 'koshi'), ('sagarmatha', 'sagarmatha'), ('Mechi', 'Mechi'), ('Janakpur', 'Janakpur'), ('Bagmati', 'Bagmati'), ('Narayani', 'Narayani'), ('Gandaki', 'Gandaki'), ('Dhawalagiri', 'Dhawalagiri'), ('Lumbini', 'Lumbini'), ('Rapti', 'Rapti'), ('Bheri', 'Bheri'), ('Karnali', 'Karnali'), ('Seti', 'Seti'), ('Mahakali', 'Mahakali')], max_length=25),
        ),
    ]
