# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundmgmt', '0014_post_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
