# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171119_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
