# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=0, max_length=10),
        ),
    ]
